# .readthedocs.yml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
  # point to your conf.py under docs/source/
  configuration: docs/source/conf.py

python:
  install:
    # 1) install Poetry itself
    - method: pip
      version: "poetry"

    # 2) use Poetry to install your package + docs extras
    - method: command
      command: poetry install --no-interaction --no-ansi --extras docs