version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    # 1) Install your docs-only dependencies
    - requirements: docs/requirements.txt

    # 2) Install your package itself (so autodoc can import it)
    - path: .
      extra_requirements:
        - docs