# .readthedocs.yml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
  # point this at your Sphinx conf.py
  configuration: docs/source/conf.py

python:
  install:
    # Install your package in editable mode,
    # plus the `docs` optional-deps group for Sphinx & extensions.
    - path: .
      method: pip
      extra_requirements:
        - docs