[project]
name = "scspecies"
version = "0.1.0"
description = "scspecies allows users to align latent representations of single-cell datasets from different species."
readme = "README.md"
long-description-content-type = "text/markdown"

requires-python = ">=3.11"
license = { text = "MIT" }

authors = [
  { name = "Clemens Schächter" },
]

homepage      = "https://scspecies.readthedocs.io/"
repository    = "https://github.com/cschaech/scspecies_package"
documentation = "https://scspecies.readthedocs.io/"

keywords = [
  "single-cell",
  "comparative analysis",
  "cross-species",
  "transfer learning",
  "alignment",
  "deep-learning",
  "scspecies",
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.11",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]

dependencies = [
  "torch (>=2.7.0,<3.0.0)",
  "muon (>=0.1.7,<0.2.0)",
  "scipy (>=1.15.3,<2.0.0)",
  "tqdm (>=4.67.1,<5.0.0)",
  "h5py (>=3.13.0,<4.0.0)",
]

[project.optional-dependencies]
plotting = [
  "seaborn (>=0.13.2,<1.0.0)",
  "glasbey (>=0.2.1,<1.0.0)",
  "matplotlib (>=3.10.1,<4.0.0)",
]
notebooks = [
  "ipywidgets (>=8.1.7,<9.0.0)",
  "ipykernel (>=6.29.5,<7.0.0)",
  "tqdm (>=4.67.1,<5.0.0)",
  "jupyter (>=1.1.1,<2.0.0)",
  "gseapy (>=1.1.8,<4.0.0)",
  "mygene (>=3.2.2,<4.0.0)",
]
docs = [
  "sphinx>=8.2",
  "sphinx-rtd-theme>=1.0",
  "myst-parser>=0.21",
  "jupyter-sphinx>=0.3",
]

[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = { find = { include = ["scspecies*"], exclude = ["docs*", "tests*", "scspecies.egg-info*"] } }